/*

 PITTSBURGHMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\RMoney\Documents\gameboy code\6A_Pittsburgh\pittsburgh.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pittsburghmapWidth 40
#define pittsburghmapHeight 18
#define pittsburghmapBank 0

extern unsigned char pittsburghmap[];

/* End of PITTSBURGHMAP.H */
