/*

 PITTSBURGHWATERFRONT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\RMoney\Documents\gameboy code\6A_Pittsburgh\pittsburgh.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pittsburghwaterfrontWidth 40
#define pittsburghwaterfrontHeight 18
#define pittsburghwaterfrontBank 0

extern unsigned char pittsburghwaterfront[];

/* End of PITTSBURGHWATERFRONT.H */
